(cl:in-package simulator-msg)
(cl:export '(GENERATOR_ID-VAL
          GENERATOR_ID
          ID-VAL
          ID
          TYPE-VAL
          TYPE
          GENERATION_DATE-VAL
          GENERATION_DATE
          GEN_TIME-VAL
          GEN_TIME
          COMPLETED_DATE-VAL
          COMPLETED_DATE
          COMPL_TIME-VAL
          COMPL_TIME
          ROUTE-VAL
          ROUTE
          SPLIT_ATTRIBUTE1-VAL
          SPLIT_ATTRIBUTE1
          SPLIT1-VAL
          SPLIT1
          SPLIT_ATTRIBUTE2-VAL
          SPLIT_ATTRIBUTE2
          SPLIT2-VAL
          SPLIT2
          SPLIT_ATTRIBUTE3-VAL
          SPLIT_ATTRIBUTE3
          SPLIT3-VAL
          SPLIT3
          ATTRIBUTE2-VAL
          ATTRIBUTE2
          VALUE2-VAL
          VALUE2
          ATTRIBUTE3-VAL
          ATTRIBUTE3
          VALUE3-VAL
          VALUE3
          LAST_EVENT-VAL
          LAST_EVENT
          FIRST_EVENT-VAL
          FIRST_EVENT
))