(cl:in-package simulator-msg)
(cl:export '(ID_NODE-VAL
          ID_NODE
          TYPE-VAL
          TYPE
          NODE_NAME-VAL
          NODE_NAME
          SERVER_TIME-VAL
          SERVER_TIME
          NUM_SERVERS-VAL
          NUM_SERVERS
          UTILIZ_TOT-VAL
          UTILIZ_TOT
          UTILIZ_ARRAY-VAL
          UTILIZ_ARRAY
          UTILIZ_ARRAY_TOT-VAL
          UTILIZ_ARRAY_TOT
          QUEUE_ARRAY-VAL
          QUEUE_ARRAY
          TIME_ARRAY-VAL
          TIME_ARRAY
          TIME_ARRAY_INTERVALS-VAL
          TIME_ARRAY_INTERVALS
          QUEUE_LEFT-VAL
          QUEUE_LEFT
          INFO-VAL
          INFO
          READY-VAL
          READY
          EVENTS_LEFT-VAL
          EVENTS_LEFT
          START-VAL
          START
          START_ESECUTION-VAL
          START_ESECUTION
          STOP_ESECUTION-VAL
          STOP_ESECUTION
          STATISTIC-VAL
          STATISTIC
))